intel/meta-acrn

recipes-core/acrn/acrn-common.inc

Ensure we only find tags like 'v1.0', otherwise the snapshot tags in the form of
'acrn-2019w19.4-140000p' are parsed as version 2019.
Signed-off-by: Ross Burton <ross.burton@intel.com>

acrn-hypervisor: add tag regex for upstream release checking

---

recipes-core/images/acrn-image-weston.bb

This enables building SOS and UOS with weston for a more accurate
comparison, as acrn-image-sato SOS produces extremely low glmark2 score.
On acrn-image-sato, glmark2-es2 score is 4x lower than
glmark2-es-wayland and thus rendering relative comparison impossible.
Signed-off-by: Chin Huat Ang <chin.huat.ang@intel.com>

acrn-image-weston: add recipe

---

.travis.yml

This is a pretty simple Travis setup that just clones Poky and verifies that the
layer parses.
Lots of future improvements, such as:
* Verify the parse against master and warrior
* Use public sstate cache and actually build
* Somehow expose the latest version check

Add initial Travis CI integration

---

.travis.yml

include meta-intel layer in travis.yml and change MACHINE to intel-corei7-64

travis: include meta-intel layer

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-tools/no-crashlog.patch
recipes-core/acrn/files/paths.patch
recipes-guests/yocto/core-image-base-package/launch-base.sh
recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

upgrade to acrn 1.4
update launch UOS script to remove acrn-dm "-c" option which
no longer applies for acrn 1.4.

acrn: upgrade to acrn 1.4

---

recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

Enables linux-intel preempt-RT kernel for real-time
uos (RTVM).
Currently pointing to Linux stable v4.19.59 and -rt24 patchset.
To enable RT kernel for uos, add below in uos.conf:
PREFERRED_PROVIDER_virtual/kernel = "linux-intel-rt-acrn-uos"

linux-intel-rt-acrn-uos/4.19: introduce preempt-RT kernel for UOS

---

classes/container-package.bbclass
conf/distro/acrn-demo-uos.conf
recipes-guests/yocto/core-image-base-package/launch-base.sh
recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

Update the launch scripts to launch User VM to directly use
the 'OVMF.fd' bios file installed by default 
in '/usr/share/acrn/bios/'

Ovmf support

---

recipes-kernel/linux/acrn-kernel-sos_4.19.bb
recipes-kernel/linux/acrn-kernel-uos_4.19.bb
recipes-kernel/linux/acrn-kernel.inc

Builds v4.19.73 (tag: v1.5.1) from projectacrn/acrn-kernel
Kernel configuration: In addition to intel-common kernel configs
from yocto-kernel-cache, sos.conf for SOS and uos.conf for UOS
is applied.
For SOS: in local.conf
PREFERRED_PROVIDER_virtual/kernel = "acrn-kernel-sos"
For UOS: in uos.conf
PREFERRED_PROVIDER_virtual/kernel = "acrn-kernel-uos"

acrn-kernel: add recipes for SOS & UOS

---

recipes-core/acrn/acrn-common.inc

For more information:
https://github.com/projectacrn/acrn-hypervisor/releases/tag/v1.5.1

acrn: update to 1.5.1

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-hypervisor-Makefile-do-not-strip.patch

acrn.efi and acrn-dm binaries are being stripped by source Makefile
in release mode, which cause below build failures:
|ERROR: QA Issue: File '/usr/lib/acrn/acrn.nuc7i7dnb.sdc.efi.out' from
acrn-hypervisor was already stripped, this will prevent future
debugging! [already-stripped]
|ERROR: QA Issue: File '/usr/bin/acrn-dm' from acrn-devicemodel
was already stripped, this will prevent future debugging! [already-stripped]
Let yocto do the stripping.

acrn-common: fix build with ACRN_RELEASE=1

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/files/0001-acrn-config-append-kconfig-setting-on-new-board.patch

dont use build/hypervisor/.config, instead use
hypervisor/arch/x86/configs/${ACRN_BOARD}.config to
prevent override.
retire oe_runmake from do_configure as no longer required.

acrn-hypervisor: dont use build/hypervisor/.config

---

recipes-core/acrn/acrn-efi-setup/acrn-efi-setup.sh

dont disable uart in efi setup script.
let ACRN_RELEASE do the job.

acrn-efi-setup: dont disable uart

---

recipes-kernel/linux/acrn-kernel.inc

recent rebase in projectacrn/acrn-kernel has removed commit ID
0bf3d99ba46b80a87f7b0f2864ba0432e34a9070 from master branch.
switch to release branch instead of master.

acrn-kernel: switch to branch release_1.5

---

conf/layer.conf

ACRN Hypervisor have dependencies on acpica version, so
it will work only with dunfell so remove all other branches

layer.conf: update LAYERSERIES_COMPAT to dunfell

---

recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

add missing LINUX_KERNEL_TYPE for linux-intel-rt-acrn-uos

linux-intel-rt-acrn-uos: add LINUX_KERNEL_TYPE

---

recipes-kernel/linux/acrn-kernel.inc
recipes-kernel/linux/files/perf-fix-build-with-binutils.patch
recipes-kernel/linux/linux-intel-acrn-sos_4.19.bb
recipes-kernel/linux/linux-intel-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-acrn.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

add necessary part to linux-intel-acrn and acrn-kernel
as meta-intel drop linux-intel 4.19 for dunfell.

linux: drop dependency on meta-intel linux-intel 4.19

---

recipes-kernel/linux/acrn-kernel-sos_4.19.bb
recipes-kernel/linux/acrn-kernel-uos_4.19.bb
recipes-kernel/linux/acrn-kernel.inc
recipes-kernel/linux/linux-intel-acrn-sos_4.19.bb
recipes-kernel/linux/linux-intel-acrn-sos_5.4.bb
recipes-kernel/linux/linux-intel-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-acrn-uos_5.4.bb
recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc

refactor linux-intel-acrn and drop dependency on meta-intel
linux-intel 5.4.

linux-intel-acrn: dont depend on meta-intel linux-intel 5.4

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/hv-lapic-minor-refine-about-init_lapic.patch

don't mask all the LVT register one by one this could be achieve
by disabling local APIC software.

acrn: dont mask all the LVT register

---

.travis.yml

By default CI builds on Ubuntu 16.04, where build complains for gcc version.
Routing build to Ubuntu 18.04

.travis.yml: switch to Ubuntu 18.04 on Travis CI

---

conf/distro/acrn-demo-uos.conf

RT uos need 2 cpu cores to start.
Signed-off-by: Gao Junhao <junhao.gao@intel.com>

acrn-demo-uos: remove maxcpus=1

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/gcc-10-disable-array-bounds-warning-for-now.patch

Disable 'array-bounds' warning for now.
Issue:
https://github.com/projectacrn/acrn-hypervisor/issues/4810

acrn-hypervisor: fix build failure due to gcc-10

---

conf/distro/acrn-demo-uos.conf
recipes-kernel/linux/files/uos_rt_5.4.scc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

add v5.4 linux-intel-rt-acrn-uos kernel and set it as default
UOS rt kernel version.

linux-intel-rt-acrn-uos: add v5.4 recipe

---

recipes-core/acrn/acrn-devicemodel.bb

keep samples, make it as saperate package so it could
be add saperately through :
IMAGE_INSTALL_append += " acrn-devicemodel-sample "

acrn-devicemodel: add package for samples

---

recipes-kernel/linux/linux-intel-acrn.inc

[zeus]linux-intel-acrn: bump to v4.19.120

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

In yocto build env, during build, kconfig not able to provide defconfig_filename(defconfig), which is set to default path 'arch/x86/configs/$BOARD.config' by hypervisor/arch/x86/Kconfig.
So in result, during make oldconfig, not able to generate .config
To fix this issue, creating harmless sample .config before compilation, which gets patched later.
Also has patch to update to latest acrn release 2.0 RC commit.

acrn-hypervisor: fix build for whl-ipc-i7

---

conf/distro/acrn-demo-sos.conf
conf/layer.conf
dynamic-layers/virtualization-layer/recipes-extended/libvirt/README
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/0001-build-drop-unnecessary-libgnu.la-reference.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/0001-ptest-Remove-Windows-1252-check-from-esxutilstest.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/configure.ac-search-for-rpc-rpc.h-in-the-sysroot.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/dnsmasq.conf
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/gnutls-helper.py
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/hook_support.py
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/install-missing-file.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/libvirt-1.0.3-fix-thread-safety-in-lxc-callback-handling.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/libvirt-use-pkg-config-to-locate-libcap.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/libvirtd.conf
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/libvirtd.sh
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/qemu-fix-crash-in-qemuOpen.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/run-ptest
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/runptest.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/tools-add-libvirt-net-rpc-to-virt-host-validate-when.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb
dynamic-layers/virtualization-layer/recipes-extended/libvirt/libvirt-python.inc

This recipe is based on libvirt recipe from meta-virtualization layer.
Fetching source from acrn-libvirt repo, which has ACRN HV support.
Added do_configure and source uri for keycodemapdb
Dropped patches, which is not required anymore.
To build this recipe, add meta-virtualization and dependency layers
in bblayers.conf.
To ship in image, add below to local.conf
IMAGE_INSTALL_append = " libvirt libvirt-libvirtd libvirt-virsh"

acrn-libvirt: add recipe

---

conf/distro/acrn-demo-sos.conf

fix unable to boot issue on grub-efi due to special character in
memmap.

acrn-demo-sos: fix memmap on grub-efi

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc

Add PCH slow clock wa for EHL GPU flr
* tag 'v5.4.46': (35 commits)
Linux 5.4.46
Revert "net/mlx5: Annotate mutex destroy for root ns"
uprobes: ensure that uprobe->offset and ->ref_ctr_offset are properly aligned
x86/speculation: Add Ivy Bridge to affected list
x86/speculation: Add SRBDS vulnerability and mitigation documentation
x86/speculation: Add Special Register Buffer Data Sampling (SRBDS) mitigation
x86/cpu: Add 'table' argument to cpu_matches()
x86/cpu: Add a steppings field to struct x86_cpu_id
x86/speculation/spectre_v2: Exclude Zhaoxin CPUs from SPECTRE_V2
nvmem: qfprom: remove incorrect write support
CDC-ACM: heed quirk also in error handling
staging: rtl8712: Fix IEEE80211_ADDBA_PARAM_BUF_SIZE_MASK
tty: hvc_console, fix crashes on parallel open/close
vt: keyboard: avoid …

linux-intel-acrn/5.4: update to 5.4.46

---

conf/distro/acrn-demo-sos.conf
recipes-core/acrn/acrn-common-dev.inc
recipes-core/acrn/acrn-devicemodel-dev.bb
recipes-core/acrn/acrn-hypervisor-dev.bb
recipes-core/acrn/acrn-tools-dev.bb

Add acrn dev recipes, which can be used to build latest
available ACRN release.
Currently points to ACRN 2.0 RC.
To select the acrn-dev provider, add below in local.conf
PREFERRED_PROVIDER_acrn-hypervisor = "acrn-hypervisor-dev"
PREFERRED_PROVIDER_acrn-devicemodel = "acrn-devicemodel-dev"
PREFERRED_PROVIDER_acrn-tools = "acrn-tools-dev"
You might need to clean up your previous build first, as Yocto does not
support provider switching.

acrn-dev: add recipes

---

conf/distro/acrn-demo-sos.conf

Supported boot parameters for acrn 1.6.1:
hvlog=2M@0x1FE00000
Supported boot parameters for acrn 2.0rc:
hvlog=2M@0xE00000 memmap=2M$0xE00000

acrn-dems-sos.conf: maintain different hvlog parameters

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

Enable storage-dir, storage-fs and storage-lvm PACKAGECONFIG
for acrn.
Received this requirement from ACRN HV team.
Installation location for storage files is $libdir/libvirt/*
To install on image, append 'libvirt-python' additonally.
IMAGE_INSTALL_append_pn-acrn-image-* = " libvirt libvirt-libvirtd libvirt-virsh libvirt-python "

acrn-libvirt: enable storage- PACKAGECONFIG

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

acrn-libvirt: safelisting fixed CVEs
CVE-2014-8135:
Fixed in v1.2.11
Fixed by: https://libvirt.org/git/?p=libvirt.git;a=commit;h=87b9437f8951f9d24f9a85c6bbfff0e54df8c984
Ref: https://security.libvirt.org/2014/0009.html
CVE-2014-8136:
Fixed in v1.2.11
Fixed by: https://libvirt.org/git/?p=libvirt.git;a=commit;h=2bdcd29c713dfedd813c89f56ae98f6f3898313d
Ref: https://security.libvirt.org/2014/0010.html
CVE-2015-5313:
Fixed in v1.3.1
Fixed by: https://libvirt.org/git/?p=libvirt.git;a=commit;h=034e47c338b13a95cf02106a3af912c1c5f818d7
Ref: https://security.libvirt.org/2015/0004.html
CVE-2017-1000256
Fixed in v3.9.0
Fixed by: https://libvirt.org/git/?p=libvirt.git;a=commit;h=441d3eb6d1be940a67ce45a286602a967601b157
Ref: https://security.libvirt.org/2017/0002.html
CVE-2018-5748:
Fixed in v4.0.0 …

acrn-libvirt: add libvirt as CVE_PRODUCT and safelist fixed CVEs

---

recipes-core/acrn/acrn-hypervisor.bb

Makefile is poor to support parallel build, facing build failure in
case of config-tool method:
| .config does not exist and no defconfig available for BOARD...
Cleanup the code which is not required with serial build.

acrn-hypervisor: dont parallel make

---

recipes-kernel/linux/files/sos.cfg

Previously SOS kernel physical start was set to 16MB, this would cause kernel
boot issue in the case that grub modules memory size is large than 15MB
(because the grub module is loaded from 1MB address so has memory overlap with
SOS load address).
In grub multiboot command, there is a --quirk-modules-after-kernel parameter
to fix this load issue, but the SOS might lost acpi environment because
multiboot does not support efi environment which includes acpi RSDP info. And
unfortunately multiboot2 command does not have --quirk-modules-after-kernel
support although it could pass efi environment to SOS.
So need to change SOS kernel load address to 128MB
(i.e.	CONFIG_PHYSICAL_START=0x8000000)
to let SOS kernel start from higher address to avoid its memory conflict with
grub modules.
Tracked-On: …

config: modify kernel physical start address

---

recipes-core/acrn/acrn-common.inc

Update to latest commit to include patch to refine pending
event inject sequence.

acrn: update to include refined pending event inject sequence

---

recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

X11 functionality with 5.4.52 breaks, it require ACRN Hypervisor patch
to support new IDV functionality coming along with 5.4.52.
This reverts commit 58948709169e13c779f341b03508193341a480be.

Revert "linux-intel-rt-acrn-uos: update to v5.4.52-rt31"

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc

X11 functionality with 5.4.52 breaks, it require ACRN Hypervisor patch
to support new IDV functionality coming along with 5.4.52.
This reverts commit 3103b51374f86561cf1a676400b1a81845bc4dc9.

Revert "linux-intel-acrn: update to 5.4.52"

---

conf/distro/acrn-demo-uos.conf

Linux kernel v5.4 introduces support for IPI shorthand, but ACRN doesn't
it with LAPIC passthroughed for now. So as a workaround, we just disable
this feature to let kernel fall back to the original implementation (send IPI one by one).
BTW, the kernel patchset for IPI shorthand support:
https://lore.kernel.org/lkml/20190722104705.550071814@linutronix.de/
Signed-off-by: Tw <wei.tan@intel.com>

linux-intel-rt-acrn-uos: fix uos shutdown issue with kernel 5.4

---

classes/acrn-sblimage.bbclass
docs/slimbootloader.md

add the image class to generate the multiboot compliant container
images which stitch ACRN Hypervisor and Operating Systems to boot with
Slim Bootloader.
Usage: Example for the ACRN hybrid scenario
1. setup meta-acrn yocto build environment by following the meta-acrn GSG
meta-intel with commit#180027 is required.
http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel/commit/?id=180027
2. add sos to BBMULTICONFIG in conf/local.conf
BBMULTICONFIG = "sos uos"
3. enable the SBL containerization feature for sos in conf/multiconfig/sos.conf
TMPDIR = "${TOPDIR}/master-acrn-sos"
DISTRO = "acrn-demo-sos"
ACRN_BOARD = "ehl-crb-b"
ACRN_SCENARIO = "hybrid"
IMAGE_CLASSES_append = " acrn-sblimage"
4. specify the module files in conf/multiconfig/sos.conf to be stitched in the container
MB_ACRN_MODULES = …

acrn-sblimage: add custom image type to inject ACRN SBL boot image

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch

Commit b5dfe36 added build for hv_prebuild(hv_prebuild_check)
before hypervisor build.
Execute hv_prebuild_check during hypervisor build can cause error :
| make:
/poky/build-acrn/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/2.1-r0/build//hypervisor/hv_prebuild_check.out:
Command not found
This is due to a hv_prebuild_check binaries build for target and execute
as native during the hypervisor make process.
The hv_prebuild_check binaries need to build as native tools so it could
execute during build, hence dont build it during hypervisor build while
make it as saperate native tools.

acrn: update to acrn-2020w33.4-180000p

---

recipes-core/acrn/acrn-hypervisor.bb

acrn-hypervisor: always deploy acrn.32.out

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

Patch file added in meta-intel linux-intel.inc in commit
"9fe38203 linux-intel: backport commit to fix perf builds"
does not compatible with 4.19 kernel and caused build error.
Hence drop it from 4.19 kernel.
Error:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['mc:uos:/2TB/yocto/poky-master/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'mc:uos:/2TB/yocto/poky-master/meta/recipes-kernel/kern-tools/kern-tools-native_git.bb:do_populate_sysroot', 'mc:uos:virtual:native:/2TB/yocto/poky-master/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['quilt-native', 'kern-tools-native', 'patch-native', 'libtool-native', 'attr-native', …

linux-intel/4.19: remove patch inherit from linux-intel.inc

---

recipes-core/acrn/acrn-hypervisor.bb

Align default SCENARIO (ACRN_SCENARIO) with upstream acrn-hypervisor.

acrn-hypervisor: industry as default scenario

---

recipes-kernel/linux/files/sos.cfg

sos kernel config: Disable IOMMU of SOS kernel
ACRN doesn't has vIOMMU feature. So we need to disable IOMMU in SOS kernel to prevent SOS kernel trying to initialize IOMMU. Otherwise, SOS IOMMU access could conflict with HV IOMMU operations and make system hang

sos kernel config: Disable IOMMU of SOS kernel

---

recipes-core/acrn/acrn-tools.bb
recipes-core/acrn/acrn-tools/add-fcommon-to-CFLAGS.patch

Fix build error due to gcc10 default to -fno-common
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=780d38ee5ecae2d7fbc44a88bc12250e45f2c79c
This is to fix the build error for now.
A long term fix needs to upstream to acrn-hypervisor
allowing CFLAGS from env to take place in all Makefile.
Error:
| /yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/10.2.0/ld: /yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/build/misc/tools/acrn-crashlog/acrnprobe/obj/android_events.o:/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/git/misc/tools/acrn-crashlog/acrnprobe/include/load_conf. …

acrn-tools: fix build error due to gcc10

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc

Also update kmeta.
Drop patch that longer applies.

linux-intel-acrn:4.19: update to 4.19.140

---

conf/layer.conf
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-acrn.inc
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-acrn-sos_5.4.bb
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-acrn-uos_5.4.bb
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-rt-acrn-uos_5.4.bb

These recipes provide support to build linux-intel-ese-lts
and linux-intel-ese-lts-rt kernel from iotg-yocto-ese-bsp layer.

linux-intel-ese-lts: add recipes

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch

Commit b5dfe36 added build for hv_prebuild(pre_build_check)
before hypervisor build.
Execute pre_build_check during hypervisor build can cause error :
| make:
/poky/build-acrn/master-acrn-sos/work/intel_corei7_64-oe-linux/acrn-hypervisor/2.1-r0/build//hypervisor/hv_prebuild_check.out:
Command not found
This is due to a pre_build_check binaries build for target and execute
as native during the hypervisor make process.
The pre_build_check binaries need to build as native tools so it could
execute during build, hence dont build it during hypervisor build while
make it as saperate native tools.
Below commits are included in this update.
acrn-config: get the max number with integer list
Makefile: modify the realpath to abspath function
HV: move vm configuration check to pre-build time
HV: …

acrn-hypervisor: update to include vm configuration check feature

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w40.1-180000p commit id. ACRN release_2.2’s RC5(final code tag)

update ACRN:acrn-2020w40.1-180000p release_2.2 RC5

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch

acrn-hyperviosr: upgrade to v2.2
Release notes:
https://projectacrn.github.io/latest/release_notes/release_notes_2.2.html
ACRN v2.2 allow to use offline tool to generate one binary of
ACPI tables for pre-launched VMs. Deploy ACPI table binaires, which
would be handy while creating sbl_os image.
Set industry as default scenario

acrn-hyperviosr: upgrade to v2.2

---

recipes-core/acrn/acrn-common.inc

This fixes warning about a trailing slash on ${S} and ${B}.

acrn: fix trailing slash in S and B

---

recipes-core/acrn/acrn-common.inc

This fixes warning about a trailing slash on ${S} and ${B}.

[master-next]acrn: fix trailing slash in S and B

---

classes/container-package.bbclass

After switching to wic, dependency on kernel:do_deploy
is redundent and it also creates circular dependencies
for dm-verity build.

container-package: drop redundant dependency

---

classes/image-acrn.bbclass
conf/distro/acrn-demo-sos.conf
wic/acrn-bootdisk-dmverity.wks.in

Configure WKS_FILE and ACRN_EFI_BOOT_CONF vars for dm-verity.

acrn-bootdisk-dmverity.wks.in: add wks for dm-verity

---

docs/dm-verity.md

WKS_FILE is being set in DISTRO based on dm-verity-img
image class.

dm-verity: update doc for dm-verity

---

classes/image-acrn.bbclass
docs/dm-verity.md

logic for ACRN_EFI_BOOT_CONF is causing error when do_image_wic.
so set it manually to avoid the error.
| ERROR: unable to parse ACRN_EFI_BOOT_CONF, in "", d)}" exiting

docs:dm-verity: set ACRN_EFI_BOOT_CONF in .conf

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

drop ACRN_FIRMWARE and acrn.efi as no longer supported.

acrn: update to acrn-2020w43.3-180000p

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-acrn.inc
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-rt-acrn-uos_5.4.bb

linux-intel-ese-lts-acrn-sos
linux-intel-ese-lts-acrn-uos
linux-intel-ese-lts-rt-acrn-uos
to inherit KERNEL_SRC_URI, SRCREV_machine  and  LINUX_VERSION from intel-ese-bsp layer

linux-intel-ese* use SRCREV from intel-ese-bsp

---

recipes-core/acrn/acrn-common.inc

updates to latest HEAD to catch logical_partition config changes
for ehl-crb-b.
latest HEAD included:
acrn-config: update logical_partition for ehl-crb-b
doc: doc fixes post 2.2 release

acrn: update config for ehl-crb-b

---

recipes-core/acrn/acrn-life-mngr.bb

Add recipe for User VM "lifecycle manager"
https://projectacrn.github.io/latest/tutorials/enable_s5.html#user-vm-lifecycle-manager
life cycle manager could be installed onto UOS by
adding below line to multiconfig/uos.conf:
IMAGE_INSTALL += " acrn-life-mngr "

acrn-life-mngr: add recipe

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-acrn.inc
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-acrn-sos_5.4.bb
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-rt-acrn-uos_5.4.bb

Enable OpenStack-related and other ACRN recommended
configs for linux-intel-ese-lts*_5.4 (SOS, UOS and RT UOS) kernels
Ported from linux-intel-acrn-* 5.4 kernel recipes.

linux-intel-ese-acrn: add configs

---

.travis.yml

oe-core master branch no longer compatible with dunfell since commit
d2e0d82f3e34a6c49066e39775572c5b8cd3c392. Hence use dunfell for oe-core
and meta-intel in travis build.

travis: use dunfell branch

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/libvirt-python.inc

Export LD*SHARED flags, required to create shared library.
In absense of LDSHARED flags, it invokes host gcc to create shared
libraries, which in result throws build failures.

acrn-libvirt: fix host gcc can't recognized option -fmacro-prefix-map

---

docs/getting-started.md

Now 'pam' has become required distro feature for weston package
when systemd is init manager, which cause below acrn build failures:
Build Error:
ERROR: Nothing RPROVIDES 'weston' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-init' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-examples' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-xwayland' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'acrn-image-weston'
ERROR: Nothing RPROVIDES 'weston' (but …

doc: document required 'pam' distro_feature for weston images

---

conf/distro/acrn-demo-sos.conf
conf/distro/acrn-demo-uos.conf

Drop invalid GVT-g kernel options which are not
valid anymore from ACRN 2.0 and higher.
Dropping i915.domain_scaler_owner option as well
for SOS.

acrn-demo: drop invalid AcrnGT kernel parameters

---

recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

With ACRN 2.2 GVT-g is not fully functional

launch-sato/weston.sh: enable GVT-d

---

recipes-core/acrn/acrn-tools.bb
recipes-core/acrn/acrn-tools/no-life-mngr.patch

dont build for life_mngr in acrn-tools.
life_mngr is for User VM while other acrn tools for Service VM
so life_mngr should be saperate from acrn-tools recipe.

acrn-tools: dont build  life_mngr

---

recipes-core/acrn/acrn-tools.bb
recipes-core/acrn/acrn-tools/no-life-mngr.patch

dont build for life_mngr.
life_mngr is for User VM while other acrn tools for Service VM
so life_mngr should be saperate recipe.

acrn-tools: no life_mngr

---

recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/acrn-config-update-function-for-xml-etree-ElementTree.patch

backport patch to fix build error on python 3.9 due to deprecated
getchildren().
Error log:
| File "acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/git/misc/acrn-config/scenario_config/../acpi_gen/asl_gen.py", line 426, in main
| for mmio_dev_node in mmio_dev_nodes.getchildren():
| AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
| make: *** No rule to make target 'update_config', needed by 'acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/build/hypervisor/.config'. Stop.
| make: Leaving directory 'acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/git/hypervisor'
| WARNING: exit code 1 from a shell …

acrn-hypervisor: fix build error on python3.9

---

recipes-core/acrn/acrn-common.inc

ACRN daily tag acrn-2021w03.1-180000p
Updated LICENSE md5sum. It has updates related to copyright years.
Signed-off-by: haribabug <haribabu.gandhamaneni@intel.com>

acrn: upgrade v2.3 -> v2.4

---

.travis.yml
conf/layer.conf
recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-devtools/python/python-kconfiglib.inc
recipes-devtools/python/python3-kconfiglib_14.1.0.bb

.travis.yml: fix meta-python dependency
python3-kconfiglib: drop recipe
This layer (meta-acrn) now depends on meta-python layer. meta-python
provides python3-kconfiglib, so no need to carry.
acrn-hypervisor: update to acrn-2021w04.3-180000p
Commits included:
2f7e0cde4 doc: update doc build instructions
329296f09 Makefile: remove rules related to Kconfig and TARGET_DIR
775214b71 Makefile: create and apply patches to generated sources
866c0881a Makefile: generate C configuration files at build time
2f6abbe75 acrn-config: add XSLT scripts to transform XMLs to config.[h|mk]
7a145253f acrn-config: add static allocators to rewrite scenario XMLs
9cff2bbdc acrn-config: add a script to generate config sources from XMLs
6c6fa5f34 Fix: HV: keep reshuffling on VBARs
5c5d27235 hv: remove …

acrn-hypervisor: update to acrn-2021w04.3-180000p

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn/5.4: update to 5.4.90
linux-intel-rt-acrn-uos/5.4: update to 5.4.87
Update kernel config to fix CONFIG_FW_LOADER mismatch warning

linux-intel-acrn/5.4: update to 5.4.90

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-rt-acrn-uos/5.4: update to 5.4.87
patchset rt48.
and 
tag 'v5.4.90': (169 commits)
Linux 5.4.90
regmap: debugfs: Fix a reversed if statement in regmap_debugfs_init()
net: drop bogus skb with CHECKSUM_PARTIAL and offset beyond end of trimmed packet
block: fix use-after-free in disk_part_iter_next
KVM: arm64: Don't access PMCR_EL0 when no PMU is available
net: mvpp2: disable force link UP during port init procedure
regulator: qcom-rpmh-regulator: correct hfsmps515 definition
wan: ds26522: select CONFIG_BITREVERSE
regmap: debugfs: Fix a memory leak when calling regmap_attach_dev
net/mlx5e: Fix two double free cases
net/mlx5e: Fix memleak in mlx5e_create_l2_table_groups
bpftool: Fix compilation failure for net.o with older glibc
iommu/intel: Fix memleak in …

  linux-intel-acrn/5.4: update to 5.4.90

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-acrn-sos_5.4.bb

Ensure SOS specific configuration override cfg inherit from ese kernel.
Also fix indentation.

linux-intel-ese-lts-acrn-sos: sos cfg always override inherited cfg

---

recipes-core/acrn/acrn-devicemodel.bb
recipes-core/acrn/acrn-hypervisor.bb

Due to recent changes, BOARD/SCENARIO take precedence over the
BOARD_FILE/SCENARIO_FILE. So BOARD_FILE/SCENARIO_FILE becomes obsolete.
Recent change, use BOARD/SCENARIO configuration variables to fetch
releated xml files automaticially.
Drop python3-konfiglib-native from DEPENDS, as kconfig is not used anymore.

acrn-hypervisor: drop BOARD_FILE/SCENARIO_FILE config variables

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-core/acrn/acrn-life-mngr.bb

Refreshed patch and updated life_mngr directory path.
Ref: https://github.com/projectacrn/acrn-hypervisor/commit/97c9b240303602141fa116d5f315c62b6958b5fa

acrn: update to tag acrn-2021w05.5-180000p

---

recipes-core/acrn/acrn-common.inc

It include fix for gcc10 compilation failure.

acrn: update to tag acrn-2021w06.3-180000p

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-rt-acrn-uos: update to v4.19.165-rt70 and v5.4.93-rt51 
linux-intel-acrn: update to v4.19.174 and  v5.4.96

[Gatesgarth] Kernel updates 

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-acrn-sos_5.4.bb

ensure sos_5.4_hybrid_rt_fusa override ese config.
get_scenario_cfg does not work for both SRC_URI and KERNEL_FEATURES so
drop it and replace with nested bb.utils.contains.

linux-intel-ese-lts-acrn-sos: ensure sos_5.4_hybrid_rt_fusa override ese config

---

recipes-kernel/linux/linux-intel-acrn-sos_5.4.bb

Clean up, use nested bb.utils.contains and add as KERNEL_FEATURES.

linux-intel-acrn-sos: fix scc filename typo

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-tools/no-life-mngr.patch

This patch updates recipes-core/acrn/acrn-tools/no-life-mngr.patch in
response to a recent update to ACRN
makefiles (projectacrn/acrn-hypervisor#5791).
Signed-off-by: Junjie Mao <junjie.mao@intel.com>

acrn: adapt to recent changes to misc/Makefile

---

classes/acrn-bootconf.bbclass
classes/image-acrn.bbclass
scripts/lib/wic/plugins/source/acrn-bootimg-efi.py

add acrn-bootconf bbclass to hold variable for boot configuration.
ACRN_EFI_BOOT_CONF can be difficult to read and write, add new variable
to allow configure boot configuration for each vm in more readable way.
VMFLAGS - list of pre-launched VM including Service vm
VM_APPEND - VM kernel commandline
KERNEL_IMAGE - kernel image like bzImage for each vm
KERNEL_MOD - kern_mod tag in acrn scenario xml for each
ACPI_TAG - ACPI tag for specific VM
ACPI_BIN - binary of ACPI tables for a specific vm
using hybrid scenario for nuc7i7dnb as example:
VMFLAGS = "vm0 vm1"
VM_APPEND_vm0 = "xxx"
KERNEL_IMAGE_vm0 = "zephyr.bin"
KERNEL_MOD_vm0 = "Zephyr_RawImage"
ACPI_TAG_vm0 = "ACPI_VM0"
ACPI_BIN_vm0 = "ACPI_VM0.bin"
VM_APPEND_vm1 = "xxx"
KERNEL_IMAGE_vm1 = "bzImage"
KERNEL_MOD_vm1 = "Linux_bzImage"
Also …

acrn-bootconf: add bbclass

---

conf/distro/acrn-demo-sos.conf
docs/getting-started.md
recipes-bsp/grub/acrn-grub-bootconf.inc
recipes-bsp/grub/grub-bootconf_1.00.bbappend

docs: update installer steps
grub-bootconf: add bbappend
Add bbappend to build grub boot menu with support for multiboot and acrn
specific setting.

Master next installer

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w13.3-180000p on ACRN release_2.4 branch.

acrn: update to tag acrn-2021w13.3-180000p

---

recipes-kernel/linux/acrn-kernel_5.4.inc

update acrn-kernel SRCREV to version 5.4.90

acrn-kernel: update acrn-kernel SRCREV to version 5.4.90

---

docs/getting-started.md

Removed wic installer note. Now wic installer works with `dunfell` too.

doc: fixed repo links

---

recipes-core/acrn/acrn-common.inc

Updated to RC6 release.
Update includes:
DM: gvt: Identical mapping for GPU DSM refine to support EHL/TGL
hv: Save/restore MSR_IA32_CSTAR during context switch
config-tools: modify sample launch scripts

acrn: update to tag acrn-2021w14.5-180000p

---

recipes-guests/yocto/core-image-base-package/launch-base.sh
recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

Ref:
https://github.com/projectacrn/acrn-hypervisor/commit/9e4fd1f1193353c5ef5043677663b9628eb8a240
As per commit:
Remove the Power Management ('pm') parameters from the sample launch scripts.
At most one VM is allowed to use "--pm_notify_channel uart"
at a time, since only one socket connection to SOS life_mngr is allowed.
Remove it by default and allow user to add on demand.
Also updated for:
core-image-sato-package
core-image-weston-package

core-image-base-package: update launch script

---

recipes-core/acrn/acrn-common.inc

This update points to release tag v2.4.
Commits included:
version:v2.4
doc: update release_2.4 with master content
Ref:
https://github.com/projectacrn/acrn-hypervisor/releases/tag/v2.4
Release notes:
https://projectacrn.github.io/latest/release_notes/release_notes_2.4.html

acrn: update to v2.4

---

classes/container-package.bbclass

Issue can be reproduced, by building SOS without multiconfig.
ERROR: core-image-sato-package-1.0-r0 do_install: Execution of
'build/master-acrn-sos/work/intel_corei7_64-oe-linux/core-image-sato-package/1.0-r0/temp/run.do_install.69656'
failed with exit code 1: install: cannot stat
'build/master-acrn-uos/deploy/images/intel-corei7-64/core-image-sato-intel-corei7-64.wic': No such file or directory

container-package: fix mcdepends, if multiconfig for sos not used

---

recipes-kernel/linux/linux-intel-acrn-sos_5.4.bb
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn-sos: fix scc filename typo
linux-intel-rt-acrn-uos/5.4: update to v5.4.102
linux-intel-acrn/5.4: update to 5.4.106

Backport kernel updates and bug fix to gatesgarth 

---

conf/distro/acrn-demo-sos.conf
dynamic-layers/virtualization-layer/recipes-extended/libvirt/libvirt-python.inc
recipes-devtools/python/python3-docutils_0.16.bb

python3-docutils: add recipe
acrn-libvirt v6.1.0, does not build with python-docutils v0.17 and higher.
This recipe will be removed once acrn-libvirt is fixed (or upgraded) for python-docutils v0.17.
######################################################################
libvirt-python: inherit python3targetconfig
libvirt shouldn't be using host's gcc to build python module, this issue
is caused by missing inherit of python3targetconfig instead added in:
https://git.openembedded.org/openembedded-core/commit/?id=5a118d4e7985fa88f04c3611f8db813f0dafce75
* otherwise libvirt build will incorrectly use host's gcc and fail with:
gcc: error: unrecognized command line option "-fmacro-prefix-map=/OE/libvirt/6.1.0-r0=/usr/src/debug/libvirt/6.1.0-r0"
This reverts commit : …

fix acrn-libvirt failure

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-build-fix-dm-and-acrn_crashlog-build-error-with-gcc-.patch

| probeutils.c:61:29: error: argument 1 of type 'char *' declared as a pointer [-Werror=array-parameter=]
| 61 | int get_uptime_string(char *newuptime, int *hours)
| | ~~~~~~^~~~~~~~~
| core/mevent.c:122:21: error: 'c' may be used uninitialized [-Werror=maybe-uninitialized]
|   122 |                 if (write(mevent_pipefd[1], &c, 1) <= 0)
|       |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In

acrn: fix gcc-11 build failures

---

recipes-core/acrn/acrn-hypervisor.bb

we can now generate the configuration and patch it before build it.
As this is not patching the original source code it does not work with
SRC_URI, so add a new variable ACRN_CONFIG_PATCH to point to the patch file.
add it to local.conf to apply the patch to the configuration:
ACRN_CONFIG_PATCH = "/path/to/config.patch"
without clang-format, patch file generated with clang-format would not
work at this point.
reference:
https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html#makefile-targets-for-configuration

acrn: add feature to patch configuration

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w21.4-180000p
It has fix for gcc-11 build failures [1].
[1] https://github.com/projectacrn/acrn-hypervisor/commit/1e033f9d89f5cd5f3f6799359b00089ee1b3ed8b

acrn: update to tag acrn-2021w21.4-180000p

---

classes/acrn-sblimage.bbclass
docs/slimbootloader.md
recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

The new efi-stub introduced to ACRN v2.5 allows booting a Slim Bootloader
Container Boot Image on UEFI-BIOS systems. Updated the recipe to generate a
boot image namely acrn.efi which combines the efi-stub application and the
sbl_os image, when both the 'acrn-sblimage' class and the 'uefi' ACRN_FIRMWARE
type is selected.
Note that the feature is only available in the ACRN 'release_2.5' branch but
not in the 'master' branch. Due to that now the 'acrn-common.inc' points to the
'release_2.5' branch.
Signed-off-by: Toshiki Nishioka <toshiki.nishioka@intel.com>

acrn: add efi-stub feature for booting sbl_os on uefi systems

---

recipes-core/acrn/acrn-common.inc

This update include following commits:
02350da92 doc: update known issues in 2.5 release notes
2b913c39e version:v2.5
cd4dc73ca doc: push doc updates for v2.5 release
7e9d62542 config_tools: remove nuc11tnbi5 scenario xml except industry.xml

acrn: update to tag v2.5

---

classes/acrn-sblimage.bbclass

The EHL uart at mmio 0xfe042000 has been defined in ehl-crb-b board file as ttyS3, so it is not needed to specify this mmio uart as hv console in hv cmdline when the ttyS3 is specified as hv console in scenario file, otherwise the hv console would be overridden when other uart is chosen as hv console.

Remove uart=mmio@0xfe042000 in the acrn-sblimage.bbclass

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-kernel/linux/acrn-kernel_5.10.inc

Tag: acrn-2021w33.2-180000p
https://github.com/projectacrn/acrn-hypervisor/releases/tag/acrn-2021w33.2-180000p
acrn-kernel/5.10: update to 5.10.52

acrn: upgrade to v2.6-unstable

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-devtools/python/python3-defusedxml_%.bbappend

ACRN release_2.6 RC1.
python3-defusedxml: add bbappend
Extend recipe to add native support.
It is new dependency introduced by:
https://github.com/projectacrn/acrn-hypervisor/pull/6343/files
This bbappend should be droped once following patch is merged upstream.
https://lists.openembedded.org/g/openembedded-devel/message/92535

acrn: update to tag acrn-2021w33.5-180000p

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn/5.4: update to v5.4.138
Updated config as well.
linux-intel-rt-acrn-uos/5.4: update to v5.4.138
Updates -rt patchset to -rt62.

linux-intel-acrn/5.4: update to v5.4.138

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-crashlog-fix-build-issue-with-e2fsprogs-v1.46.2.patch

Issue thrown with e2fsprogs v1.46.2.
Patch applied to fix.
Error log:
loop.c: In function 'loopdev_check_parname':
loop.c:234:33: error: 'strcmp' argument 1 declared attribute 'nonstring' [-Werror=stringop-overread]
234 |                         return !strcmp((const char *)super.s_volume_name, parname);
|
make[2]: Leaving directory '/home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-corei7-64-acrn-image-sato-linux-intel-default-kernel/build/build/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.5-r0/git/misc/services/acrn_manager'
loop.c: In function 'loopdev_check_parname':
loop.c:234:33: error: 'strcmp' argument 1 declared attribute 'nonstring' [-Werror=stringop-overread]
234 |                         return !strcmp((const char *)super.s_volume_name, parname);
| …

acrn: fix build failure with e2fsprogs v1.46.2

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel/dont-build-tools.patch

do not build tools while building devicemode.Tools are
built using seperate recipe and made available
during devicemodel build using DEPENDS
Refreshed patch.
It also update recipe to include lastest commits:
9bf80f916 dm: pci: destory reseverd PIO BAR when deinit passthrough PCI device
f83d78225 hv: pci: fix a minor bug about is_pci_cfg_multifunction
1c61872ef dm: pci: minor bug fix about uninitialized local variable
0b63f3378 Makefile: add missing deps in top-level and hypervisor Makefile

acrn: update to tag acrn-2021w38.1-180000p

---

recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

launch-weston.sh: enable GVT-d
With ACRN 2.2 GVT-g is not fully functional
(cherry picked from commit a9ebd56117a0f3e87a120072ce0a3de7a84aaf7c)
Signed-off-by: Lee Chee Yang <Chee.Yang.Lee@intel.com>

launch-sato.sh: enable GVT-d

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb
recipes-kernel/linux/acrn-kernel_5.10.inc

acrn-kernel/5.10: include libvirt patches
This update includes:
1c1a7f4768f9 virt: acrn: add acrn hypervisor log back
a7878a2c4234 virt: acrn: update HSM ioctl about platform info getting
92d5bb205405 config: remove kernel physical start address
e381af0b6aa1 config: Enabled Intel I225 NIC PTM capability
7fa58bb554f2 config: add AST driver(ASPEED GPU)
acrn-libvirt: update to include fix platform info and offline cpu issue
https://github.com/projectacrn/acrn-libvirt/commit/76cc3a01580349cfb5d2eaf7159d959990070313

Fix acrn-libvirt failure with acrn-kernel/5.10

---

recipes-core/acrn/acrn-common.inc

https://github.com/projectacrn/acrn-hypervisor/releases/tag/v2.6
It also update recipe to include lastest commits:
f5935afc4 version:2.6
c3473b589 config_tools: schema: revert to old schema
e678dc8e7 doc: pick doc updates for v2.6 release
eade39758 Makefile: fix wrong reference to board XML and skip binary in diffconfig

acrn: update to tag v2.6

---

conf/layer.conf
docs/getting-started.md
docs/qa.md
docs/references.md
docs/slimbootloader.md

layer.conf: drop gatesgarth support
Building with oe-core gatesgarth is no longer supported. Remove from
LAYERSERIES_COMPAT

docs: update for honister release

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-tools.bb
recipes-core/acrn/files/0001-acrnprobe-supress-openssl-3.0-deprecated-declaration.patch

Fix build failure by supressing warnings until its fixed upstream.

acrn: supress openssl 3.0 deprecated-declarations warnings for now

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb
recipes-core/acrn/acrn-common.inc

Add branch name explicitly to SRC_URI where it's not defined and
switch to using https protocol for Github projects.
OE-Core now has a QA check to see if /var/log is empty. Since /var/log
is usually a symlink to /var/volatile/log, anything installed here won't actually be available.
Remove the directory.
acrn: specify https protocol to avoid warnings
Add branch name explicitly to SRC_URI where it's not defined and
switch to using https protocol for Github projects.

acrn-libvirt: specify branch and https protocol to avoid warnings

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb
recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

acrn: fix warning
Remove unnecessary "+=". Bitbake is now warning when "+=" is used with
append, as it is not recommended combination.
###################################################
acrn-libvirt: specify branch and https protocol to avoid warnings
Add branch name explicitly to SRC_URI where it's not defined and
switch to using https protocol for Github projects.
OE-Core now has a QA check to see if /var/log is empty. Since /var/log
is usually a symlink to /var/volatile/log, anything installed here won't actually be available.
Remove the directory.
###################################################
acrn: specify https protocol to avoid warnings
Add branch name …

Fix https and syntax warnings and specify branches

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

This update includes:
acrn-driver: don't pass UUID to acrn-dm
acrn-driver: update calculation of cpu affinity and UUID
acrn-driver: enable related auto start commands
acrn-driver: add call back to check guest persistent

acrn-libvirt: update to include latest commits

---

conf/distro/acrn-demo-sos.conf
recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-kernel/linux/acrn-kernel_5.10.inc

ACRN 2.7 RC1
Switched to release_2.7 branch.
Removed hvlog and memmap parameters from acrn commandline(Service VM bootargs)[1].
[1]
https://github.com/projectacrn/acrn-hypervisor/commit/3124097a787a949ea9d433340326f838b58cd19d
https://github.com/projectacrn/acrn-hypervisor/pull/6718
https://github.com/projectacrn/acrn-hypervisor/issues/6663
###################################
acrn-kernel/5.10: update to 5.10.65
Switched to release_2.7 branch.

acrn: update to daily tag acrn-2021w46.3-180000p

---

recipes-bsp/setserial/setserial/setserial
recipes-bsp/setserial/setserial/setserial.service
recipes-bsp/setserial/setserial_%.bbappend

Add setserial.service to configure non-standard COM Ports
in service VM. These non-standard COM ports are required
for communication between service VM and user VMs.

setserial: add bbappend

---

recipes-core/acrn/acrn-common.inc
recipes-guests/yocto/core-image-base-package/launch-base.sh
recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

ACRN 2.7 RC3
##################################################
launch-script: add --cpu_affinity acrn-dm parameter
Assign physical CPUs (pCPUs) to post-lauched VM.
Note: Guest VM launch script should be generated using config-tools
This layer carryies sample lauch scripts with works with default nuc11tnbi5 board and shared scenario.
Ref:
https://github.com/projectacrn/acrn-hypervisor/blob/release_2.7/misc/config_tools/data/nuc11tnbi5/shared.xml#L119
https://projectacrn.github.io/latest/user-guides/acrn-dm-parameters.html?highlight=cpu_affinity

acrn: update to tag acrn-2021w48.4-180000p

---

recipes-core/acrn/acrn-hypervisor.bb

scripts/lnr has been removed. So use `ln --relative --symlink` from coreutils
to create relative symlinks, instead.
#######################################################
acrn-hypervisor: fix syntax warning
Remove unnecessary "+="

acrn-hypervisor: fix lnr command not found issue

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

ACRN 2.7 RC5
#######################################
acrn-hypervisor: fix lnr command not found issue
scripts/lnr has been removed. So use `ln --relative --symlink` from coreutils
to create relative symlinks, instead.

acrn: update to tag acrn-2021w49.4-180000p

---

recipes-core/acrn/acrn-common.inc

Fix is already available in ACRN v2.5.1
https://github.com/projectacrn/acrn-hypervisor/commit/f4b93f31b7e108d51bc1156ee4feacbc94a602f1

acrn-hypervisor: passlist CVE-2021-36145

---

recipes-kernel/linux/linux-intel-acrn-sos_5.10.bb
recipes-kernel/linux/linux-intel-acrn-uos_5.10.bb
recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb

linux-intel-acrn-sos/5.10: add recipe
Add recipe to build LTS 5.10 Kernel for Service VM.
######################################################
linux-intel-acrn-uos/5.10: add recipe
Add recipe to build LTS 5.10 kernel for Guest VM.
######################################################
linux-intel-rt-acrn-uos/5.10: add recipe
Add recipe to build 5.10 RT kernel for Guest VM.

linux-intel-acrn-sos/5.10: add recipe

---

recipes-core/acrn/acrn-common.inc

Release tag:
https://github.com/projectacrn/acrn-hypervisor/releases/tag/v2.7
Release notes:
https://projectacrn.github.io/latest/release_notes/release_notes_2.7.html

acrn: update to release tag v2.7

---

conf/distro/acrn-demo-sos.conf
conf/distro/acrn-demo-uos.conf

Kernel 5.4 support has been dropped.

distro: set 5.10 kernel as default

---

recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb

Updated kernel config too.
v5.10.90: (228 commits)
Revert "drm/ast: potential dereference of null pointer"
Revert "drm/amd/pm: fix a potential gpu_metrics_table memory leak"
Revert "drm/amdgpu: correct register access for RLC_JUMP_TABLE_RESTORE"
Revert "drm/amdgpu: When the VCN(1.0) block is suspended, powergating is explicitly enabled"
Revert "drm/amdgpu: add support for IP discovery gc_info table v2"
Linux 5.10.90
bpf: Add kconfig knob for disabling unpriv bpf by default
perf script: Fix CPU filtering of a script's switch events
net: fix use-after-free in tw_timer_handler
Input: spaceball - fix parsing of movement data packets
Input: appletouch - initialize work before device registration
scsi: vmw_pvscsi: Set residual data length conditionally
binder: fix async_free_space accounting …

linux-intel-acrn/5.10: update to 5.10.90

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt/Fix-template-matching-in-page.xsl.patch
dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

Backport patch from Libvirt to fix compile error 

acrn-libvirt: fix compile error

---

recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn: update to 5.10.100
update to lts-v5.10.100-yocto-220223T232711Z.
also update kernel cache.
#####################################################
linux-intel-rt-acrn-uos : update to 5.10.100-rt62
update to lts-v5.10.100-rt62-preempt-rt-220226T032749Z.
also update kmeta.
######################################################
linux-intel-rt-acrn-uos: update to 5.4.177
update to lts-v5.4.177-rt69-preempt-rt-220210T012802Z.
also update kmeta.
Signed-off-by: Naveen Saini …

Master next update

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-Makefile-disable-Werror-option-for-now.patch
recipes-core/acrn/files/0001-hv-crypto-fix-a-minor-build-Werror.patch

GCC12 causing multiple warnings which are currently being treated as error.
So disabling -Werror option for now

acrn: fix gcc-12 failures

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-Makefile-disable-Werror-option-for-now.patch
recipes-core/acrn/files/0001-misc-acrnd-fix-a-minor-build-Werror.patch

GCC12 causing multiple warnings which are currently being treated as error.
Ignore for now, untill not fixed upstream.
Open Issue: https://github.com/projectacrn/acrn-hypervisor/issues/7453

acrn-life-mngr: fix build failure due to gcc-12

---

recipes-kernel/linux/files/0001-regulator-consumer-Add-missing-stubs-to-regulator-co.patch
recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

f226b95 linux-intel-rt-acrn-uos/5.4 : update to 5.4.193-rt74
0c74fc3 linux-intel-rt-acrn-uos : update to 5.10.115-rt67
1b0cf25 linux-intel-acrn/5.10: update to v5.10.115

linux-intel-acrn/5.10: update to v5.10.115

---

conf/distro/acrn-demo-sos.conf

DHCP is already enabled & handled by ACRN bridge services, which
causes conflict with it. Due to that user VM do not get
IP address. So disable it, let ACRN tools handle it.
https://git.yoctoproject.org/poky/tree/meta/recipes-core/systemd/systemd-conf_1.0.bb#n26
https://github.com/projectacrn/acrn-hypervisor/tree/release_3.0/misc/services/acrn_bridge

acrn-demo-sos.conf: Disable auto ethernet DHCP

---

conf/distro/acrn-demo-sos.conf
conf/distro/include/acrn-demo.inc

acrn-demo-sos.conf: Disable auto ethernet DHCP
DHCP is already enabled & handled by ACRN bridge services, which
causes conflict with it. Due to that user VM do not get
IP address. So disable it, let ACRN tools handle it.
https://git.yoctoproject.org/poky/tree/meta/recipes-core/systemd/systemd-conf_1.0.bb#n26
https://github.com/projectacrn/acrn-hypervisor/tree/release_3.0/misc/services/acrn_bridge
##########################################################################
acrn-demo.inc: Version bump to 4.0
Bump version post kirkstone release

Backport patches from master

---

scripts/lib/wic/plugins/source/acrn-bootimg-efi.py

Fix 'Imporper Resource Shutdown or Release' issue thrown by
CHECKMARX scanning

acrn-bootimg-efi.py: close file correctly

---

recipes-kernel/linux/acrn-kernel_5.15.inc

acrn-kernel master update to 5.15 for ACRN v3.1

acrn-kernel master update to 5.15.44

---

recipes-kernel/linux/files/service-vm_5.15.cfg
recipes-kernel/linux/files/service-vm_5.15.scc
recipes-kernel/linux/files/user-rtvm_5.15.scc
recipes-kernel/linux/files/user-vm_5.15.cfg
recipes-kernel/linux/files/user-vm_5.15.scc
recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn-service-vm_5.15.bb
recipes-kernel/linux/linux-intel-acrn-user-vm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

linux-intel-acrn-service-vm/5.15: add recipe for service VM
Add linux-intel-acrn-user-vm/5.15 kernel recipe for User VM too.
##########################################################
linux-intel-acrn-rtvm/5.15: add recipe for RTVM

linux-intel-acrn-service-vm/5.15: add recipe for service VM

---

recipes-core/acrn/acrn-common.inc

Updated to ACRN 3.1 RC1 release.

acrn: switch to release_3.1 branch

---

recipes-core/acrn/acrn-life-mngr.bb

It fixes life_mngr.service failure.

acrn-life-mngr: install life_mngr.conf

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch
recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn-service-vm_5.15.bb
recipes-kernel/linux/linux-intel-acrn-user-vm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

f9ef2fd acrn: upgrade to v3.2
929e4fb linux-intel-acrn-rtvm/5.15: add recipe for RTVM
fc51235 linux-intel-acrn-service-vm/5.15: add recipe for service VM
20db93c acrn: upgrade to releaes tag v3.1

Backport kernel 5.15 patches

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

Added linux-intel-lts repo path, its required due to recent changes in meta-intel layer.
https://git.yoctoproject.org/meta-intel/commit/?id=2ce9b55f99a30e810aed196888c0858f4996e26e

linux-intel-acrn/5.15: fix SRC_URI

---

conf/distro/acrn-demo-service-vm.conf
recipes-devtools/python/python3-elementpath_3.0.2.bb

elementpath 4.0.1 has removed 'SYMBOLS' attribute, which causing failure in ACRN 3.1.0 https://github.com/sissaschool/elementpath/commit/a76aeb88b0d103420239df1d5d001f7d7f56b5c9
misc/config_tools/scenario_config/elementpath_overlay.py", line 24, in CustomParser
|     SYMBOLS = BaseParser.SYMBOLS | {
|               ^^^^^^^^^^^^^^^^^^
| AttributeError: type object 'XPath2Parser' has no attribute 'SYMBOLS'
Issue raised: https://github.com/projectacrn/acrn-hypervisor/issues/8368
Carry python3-elementpath 3.0.2 version locally, until it gets fixed upstream

python3-elementpath/3.0.2: add recipe

---

recipes-kernel/linux/files/0001-menuconfig-mconf-cfg-Allow-specification-of-ncurses-.patch

Recently meta-intel removed this patch along with 5.15 kernel support.
https://git.yoctoproject.org/meta-intel/commit/?id=03229249889f621577b211de2d5c4d12914c341b

linux-intel/5.15: carry patch locally

---

recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/0001-hypervisor-Makefile-ignore-warning-due-to-gcc-13.patch

Error:
| In function 'partition_epc',
|     inlined from 'init_sgx' at arch/x86/sgx.c:116:19:
|   [-Werror=maybe-uninitialized]
|    86 |                         vm_epc_maps[mid][vm_id].gpa = vm_config->epc.base + vm_config->epc.size - vm_request_size;
|       |                                                                             ~~~~~~~~~~~~~~^~~~~
| arch/x86/sgx.c: In function 'init_sgx':
| arch/x86/sgx.c:61:32: note: 'vm_config' was declared here
|    61 |         struct acrn_vm_config *vm_config;
|       |                                ^~~~~~~~~
| cc1: all warnings being treated as errors
Issue raised. https://github.com/projectacrn/acrn-hypervisor/issues/8413 Ignore fow now, until fixed upstream.

acrn-hypervisor: ignore warning due to gcc-13

---

classes/container-package.bbclass

Due to recent commit:
https://git.yoctoproject.org/poky/commit/?id=6f6c79029bc2020907295858449c725952d560a1
Error:
install: cannot stat '/build/master-acrn-uos/deploy/images/intel-corei7-64/core-image-base-intel-corei7-64.wic': No such file or directory
Add 'rootfs' suffix

container-package: fix guest vm image path

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.19.bb
recipes-kernel/linux/linux-intel-acrn_5.19.inc

Tags:
mainline-tracking-v5.19-linux-230814T122132Z
mainline-tracking-v5.19-rt10-preempt-rt-230815T033653Z

linux-intel-acrn/5.19: update kernel recipe

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

Image built is verified to work as expected on ADL. But this need to build with the new xmls which is still in PR in meta-qa.
https://cbjenkins-pg.devtools.intel.com/teams-iotgdevops01/job/iotgdevops01/view/COREOS/job/GEN-LIN-COREOS.I7.64.ACRN.SATO.INTEL.RT.DEFAULT.KERNEL-BD-DLY/653/

linux-intel-acrn/5.15: update to v5.15.129

---

conf/distro/acrn-demo-service-vm.conf
recipes-devtools/python/python3-xmlschema_3.0.1.bb

Newer version throw errors. Carry this recipe until issue is fixed in upstream.
TypeError: build_schema_node_tree() got an unexpected keyword argument 'uri'

python3-xmlschema/3.0.1: add recipe

---

conf/distro/include/acrn-demo.inc
recipes-core/acrn/acrn-common.inc

TCLIBCAPPEND has been deprecated.
https://git.yoctoproject.org/poky/commit/?id=099c09be3c37743425486664c6457bd0301c74f0
Skip buildpaths QA checks for ACRN recipes.

acrn-demo.inc: remove TCLIBCAPPEND

---

recipes-bsp/setserial/setserial_%.bbappend

install: cannot stat 'build/master-acrn-sos/work/corei7-64-oe-linux/setserial/2.17/setserial': No such file or directory

setserial: fix build failure

---

recipes-core/acrn/acrn-common.inc

Warnings:
CVE_CHECK_IGNORE is deprecated in favor of CVE_STATUS

acrn: Fix CVE_CHECK_IGNORE is deprecated warnings
