recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/paths.patch
recipes-kernel/linux/linux-intel-acrn.inc

these patches
1. upgrade acrn recipes to acrn 1.1
2. update docs to use variable for path

upgrade to acrn 1.1

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel/dont-build-tools.patch
recipes-core/acrn/acrn-hypervisor.bb
recipes-core/acrn/acrn-hypervisor/efi-loader.patch
recipes-core/acrn/acrn-tools/no-crashlog.patch
recipes-core/acrn/files/paths.patch

acrn: update to v1.2

---

docs/getting-started.md

docs: add steps to build installer image

---

docs/qa.md
docs/references.md

docs: update url to v1.3

---

.travis.yml

travis: include yocto-check-layer

---

recipes-core/packagegroups/packagegroup-acrn.bb

Remove deprecated distro_features_check

packagegroup-acrn: use features_check

---

conf/layer.conf

layer.conf: add meta-intel to layer depends list

---

recipes-devtools/python/python-kconfiglib.inc
recipes-devtools/python/python3-kconfiglib_10.42.0.bb
recipes-devtools/python/python3-kconfiglib_13.7.0.bb

python-kconfiglib: update to 13.7.0

---

docs/qa.md
docs/references.md

docs: update url to v1.5

---

docs/getting-started.md

include brief explaination and steps on kernel selection.

docs: include kernel setting

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/Fix-build-issue-if-the-ld-is-updated-to-2.34.patch

acrn: fix build error after binutils update

---

recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

linux-intel-rt-acrn-uos: update to 4.19.94

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump version for 3.0 zeus release

---

conf/distro/include/acrn-demo.inc

Later with release branch it will bumped to specific version

acrn-demo: set distro version

---

.travis.yml

Add meta-openembedded/meta-oe in bblayer for efibootmgr

travis.yml: switch to warrior branch

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump version for 2.7 warrior release

---

recipes-guests/yocto/core-image-base-package/launch-base.sh
recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

update launch UOS script to align with acrn-hypervisor sample
script for nuc.

core-image-*-package: update launch uos script

---

recipes-core/acrn/acrn-common.inc

acrn-hypervisor: set CVE_PRODUCT to include vendor

---

recipes-core/acrn/acrn-common.inc

acrn-hypervisor: Whitelist CVE-2019-18844

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/0001-acrn-config-append-kconfig-setting-on-new-board.patch

acrn: revert patch remove in v1.6 upgrade

---

recipes-kernel/linux/acrn-kernel.inc

acrn-kernel: upgrade to 4.19.106(v1.6)

---

recipes-core/acrn/acrn-tools.bb
recipes-core/acrn/acrn-tools/avoid-race-condition.patch

Issue is observed while building acrn-crashlog.
Patch is applied.

acrn-tools: avoid race condition

---

.travis.yml

travis: test against zeus branch

---

conf/layer.conf
custom-licenses/Intel
recipes-core/acrn/acrn-tools.bb
recipes-core/packagegroups/packagegroup-acrn.bb
recipes-extended/acpica/acpica_20200214.bb

This patch series allows to build against zeus release.

add compatibility for zeus

---

conf/layer.conf
custom-licenses/Intel
recipes-core/acrn/acrn-tools.bb
recipes-core/packagegroups/packagegroup-acrn.bb
recipes-extended/acpica/acpica_20200214.bb

This patch series allows to build against zeus release.

add compatibility for zeus 

---

docs/getting-started.md
docs/qa.md
docs/references.md

docs: update documentation for Acrn v1.6

---

conf/distro/acrn-demo-sos.conf
conf/distro/acrn-demo-uos.conf
docs/getting-started.md

use PREFERRED_VERSION for version.

docs & conf : fix typo

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump version for 3.1 dunfell release

---

recipes-core/acrn/acrn-common.inc

acrn: upgrade to v1.6.1

---

docs/getting-started.md

current build steps affected UOS if UOS build using multiconfig
refine build steps to use multiconfig for installer

docs: refine installer build steps

---

conf/distro/acrn-demo-uos.conf

RT uos need 2 cores to start.
Signed-off-by: Gao Junhao <junhao.gao@intel.com>

acrn-demo-uos: remove maxcpus=1

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc

[dunfell] linux-intel-acrn : bump to 4.19.120

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc

linux-intel-acrn: bump to 5.4.39

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc

linux-intel-acrn : bump to 4.19.120

---

docs/getting-started.md

doc: update for linuxt-intel 5.4 preempt RT support

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/files/paths-master.patch

see commit
https://github.com/projectacrn/acrn-hypervisor/commit/0f6d11866b41d54044bbe9ac16f3cfbe039d0fd9

acrn: point to latest commit

---

recipes-core/acrn/acrn-common.inc

allow variable SRCBRANCH to change source branch.

acrn-common: add variable SRCBRANCH

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: post release version bump

---

recipes-core/acrn/acrn-common.inc

acrn-hypervisor: update to latest commit

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

Enable recommended packageconfig for acrn drivers.

acrn-libvirt: update to latest commit

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc

linux-intel-acrn: update to tag lts-v5.4.46-yocto-200622T202915Z

---

docs/getting-started.md

docs: describe acrn-hv version selection

---

docs/getting-started.md

doc: libvirt configuration

---

docs/getting-started.md
docs/qa.md
docs/references.md

add libvirt configuration 
updates url
remove/update old documentation

docs: updates

---

recipes-core/acrn/acrn-common.inc

acrn: 2.0rc to 2.0

---

recipes-core/acrn/acrn-common-dev.inc

acrn:dev: 2.0rc -> 2.0

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

linux-intel-acrn-uos update to v4.19.130 
linux-intel-acrn update to 5.4.52
linux-intel-rt-acrn-uos update to v4.19.130-rt57

[master] several kernel updates

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb

linux-intel-acrn-uos update to v4.19.130 
linux-intel-rt-acrn-uos update to v4.19.130-rt57

[dunfell] kernel updates to 4.19.130 & 4.19.130-rt57

---

recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-rt-acrn-uos: update to v5.4.52-rt31

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn update to 5.4.52 
linux-intel-rt-acrn-uos update to v5.4.52-rt31

kernel updates to v5.4.52 & v5.4.52-rt31

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc

linux-intel-acrn:5.4: update to 5.4.58

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc

linux-intel-acrn:4.19: update to 4.19.140

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

update linux-intel-acrn to 5.4.58
update linux-intel-rt-acrn-uos to v5.4.58-rt35

[Dunfell] 5.4 kernel update

---

recipes-core/acrn/acrn-common.inc

update ACRN: acrn-2020w37.4-180000p ACRN release_2.2 RC1

ACRN: acrn-2020w37.4-180000p ACRN release_2.2 RC1

---

recipes-core/acrn/acrn-common.inc

acrn-common.inc: switch to release_2.2 branch

---

conf/distro/acrn-demo-uos.conf

acrn-demo-uos: apply LINUX_RT_APPEND to linux-intel-ese-lts-rt-acrn-uos

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w38.3-180000p commit id.

update ACRN:acrn-2020w38.3-180000p release_2.2 RC1

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

update linux-intel-acrn to 5.4.68 and 4.19.145.
update linux-intel-rt-acrn-uos to 4.19.142-rt63 and 5.4.66-rt38

[master] multiple kernel update

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

update linux-intel-acrn to 5.4.68 and 4.19.145.
update linux-intel-rt-acrn-uos to 4.19.142-rt63 and 5.4.66-rt38

[master-next] multiple kernel update

---

docs/dm-verity.md

dm-verity.md: add doc to enable dm-verity

---

recipes-support/numactl/numactl_git.bb

update numactl to 2.0.14

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w45.3-180000p on release_2.3.

update ACRN:acrn-2020w45.3-180000p on release_2.3

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w45.5-180000p on ACRN release_2.3 RC4.

update ACRN:acrn-2020w45.5-180000p on release_2.3

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w46.3-180000p on ACRN release_2.3 RC5.

update ACRN:acrn-2020w46.3-180000p on release_2.3

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn update to 5.4.75 and 4.19.152
linux-intel-rt-acrn-uos update to v5.4.70-rt40 and  v4.19.152-rt65

Kernel Updates

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w47.2-180000p on ACRN release_2.3 RC6.

update ACRN:acrn-2020w47.2-180000p on release_2.3

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn update to 5.4.75 and 4.19.152
linux-intel-rt-acrn-uos update to v5.4.70-rt40 and v4.19.152-rt65

[Master] kernel updates

---

docs/getting-started.md
docs/qa.md
docs/references.md
docs/slimbootloader.md

docs: update for gatsgarth release

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump distro version for 3.2 gatesgarth release

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2020w48.5-180000p on ACRN release_2.3 RC7.

update ACRN:acrn-2020w48.4-180000p on release_2.3

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-rt-acrn-uos_5.4.bb

change stmmac build-in to module

change stmmac build-in to module

---

dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-acrn.inc
dynamic-layers/intel-ese-bsp/recipes-kernel/linux/linux-intel-ese-lts-rt-acrn-uos_5.4.bb
recipes-kernel/linux/linux-intel-acrn-sos_5.4.bb
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-*: insert spaces

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

Also drop ACRN_FIRMWARE variable.

acrn: update to 2.3

---

recipes-core/acrn/acrn-common.inc

acrn: update to acrn-2020w51.5-180000p

acrn: update to acrn-2020w51.5-180000p

---

recipes-kernel/linux/linux-intel-acrn_4.19.inc
recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_4.19.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-acrn updates to 4.19.163 and 5.4.81
linux-intel-rt-acrn-uos updates to v4.19.160-rt69 and 5.4.78-rt44

[gatesgarth] kernel updates

---

docs/getting-started.md

Also update doc for distro configuration override.

doc: update for meta-python layer dependency

---

docs/getting-started.md

Fix typo
Add libvirt-pyton
Clean up

doc: update documentation

---

recipes-kernel/linux/acrn-kernel-sos_5.4.bb
recipes-kernel/linux/acrn-kernel-uos_5.4.bb
recipes-kernel/linux/acrn-kernel_5.4.inc

add acrn-kernel 5.4 recipe

---

classes/acrn-sblimage.bbclass
classes/container-package.bbclass
docs/slimbootloader.md

added code to support multiboot configuration while packaging the SBL OSContainer

added code to support multiboot configuration

---

docs/logical-partition.md

Signed-off-by: Lee Chee Yang <Chee.Yang.Lee@intel.com>

docs: add example to setup for logical partition scenario

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-rt-acrn-uos: update to v5.4.93-rt51 
linux-intel-acrn: update to v5.4.96

Updates Kernel

---

conf/distro/acrn-demo-sos.conf
docs/getting-started.md
recipes-bsp/grub/acrn-grub-bootconf.inc
recipes-bsp/grub/grub-bootconf_1.00.bbappend

update docs to build installer
also add grub-bootconf bbappend to update grub.cfg with acrn boot option

update installer steps 

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w10.1-180000p on ACRN release_2.4.

update ACRN:acrn-2021w10.1-180000p on release_2.4

---

recipes-core/acrn/acrn-common.inc

acrn: update to tag acrn-2021w11.3-180000p

---

docs/getting-started.md

doc: update doc for grub configuration variables

---

conf/layer.conf

layer.conf: add hardknott to LAYERSERIES_COMPAT

---

recipes-core/acrn/acrn-common.inc

This update includes:
hv: ptirq: Shouldn't change sid if intx irq mapping was added

acrn: update to include latest commit

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-tools.bb

Ref:
https://github.com/projectacrn/acrn-hypervisor/commit/d5f1a44d65e2a39a019fb668ae241afc9ab207ae

acrn: set ACRN_RELEASE=y|n instead of 0|1

---

docs/getting-started.md

doc: update and re-structure documenation

---

docs/getting-started.md

Reviewed-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
Reviewed-by: Benjamin Fitch <benjamin.fitch@intel.com>

doc: update and re-structure documentation

---

recipes-kernel/linux/linux-intel-acrn_5.4.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

linux-intel-rt-acrn-uos/5.4: update to v5.4.102
Updated kernel config.

linux-intel-acrn/5.4: update to 5.4.106

---

docs/getting-started.md
docs/qa.md
docs/references.md

Ref:
https://projectacrn.github.io/2.4/

doc: update web link for ACRN 2.4

---

conf/layer.conf

layer.conf: drop gatesgarth and dunfell for hrdknott release

---

docs/getting-started.md

docs: update for hardknott release

---

.travis.yml
conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump distro version for 3.3 hardknott release
.travis.yml: switch to hardknott

acrn-demo.inc: Bump distro version for 3.3 hardknott release

---

recipes-core/acrn/acrn-common.inc

It includes a devicemodel issue fix[1]
https://github.com/projectacrn/acrn-hypervisor/commit/ade36db37775c498d7d3a9322d9e69b37355b995
[1] https://github.com/projectacrn/acrn-hypervisor/issues/5973

acrn: update to tag/v2.4.0.1

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w19.6-180000p

acrn: update to tag acrn-2021w19.6-180000p

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w23.5-180000p.

acrn: update to tag acrn-2021w23.5-180000p

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w24.5-180000p

acrn: update to tag acrn-2021w24.5-180000p

---

docs/dm-verity.md

Ref:
https://github.com/intel/meta-acrn/commit/0ba6e9a484d85771a10e1e2eb4173a164432d93b

docs/dm-verity.md: udpate build steps

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w25.5-180000p

acrn: update to tag acrn-2021w25.5-180000p

---

recipes-guests/yocto/core-image-base-package/launch-base.sh

This is compatible only with kernel 5.10.
https://github.com/projectacrn/acrn-hypervisor/commit/1bccfab3b69fc813bb37d7fd8efd8d6f0227e28c

core-image-base-package: update launch script

---

recipes-core/acrn/acrn-common.inc

Ref:
https://github.com/projectacrn/acrn-hypervisor/releases/tag/acrn-2021w34.5-180000p

acrn: update to tag acrn-2021w34.5-180000p

---

recipes-core/acrn/acrn-common.inc

updated with the ACRN daily tag acrn-2021w37.3-180000p

acrn: update to tag acrn-2021w37.3-180000p

---

recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

core-image-weston-package: update launch script
This is compatible only with kernel 5.10.
https://github.com/projectacrn/acrn-hypervisor/commit/1bccfab3b69fc813bb37d7fd8efd8d6f0227e28c

core-image-sato-package: update launch script

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Bump distro version for 3.4 honister release

---

recipes-kernel/linux/linux-intel-acrn-sos_5.10.bb
recipes-kernel/linux/linux-intel-acrn_5.10.inc

linux-intel-acrn-sos/5.10: add recipe

---

recipes-core/acrn/acrn-common.inc

acrn: update to tag acrn-2021w47.4-180000p

---

docs/getting-started.md

Update guide for default board & scenario values too
Ref:
https://github.com/intel/meta-acrn/commit/93629f0d4007bb5fc308d1089aebab8b854bd734
https://github.com/intel/meta-acrn/commit/cd6cc76acdda62f566e8720434ce08c9e2a53492
https://github.com/intel/meta-acrn/commit/627df1ef3c156b9ee6a98c7788b0f642fb5d30c3

doc: update document for grub cfg enhancement

---

docs/getting-started.md

doc: update getting started guide

---

docs/getting-started.md

doc: update for 5.4 RT kernel support for Guest VMs

---

conf/layer.conf

layer: add kirkstone support

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb
recipes-devtools/python/python3-docutils_0.16.bb

meta : update LICENSE to use SPDX identifiers

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

acrn-libvirt: update to acrn-r2.7-v6.1.0

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel.bb

add dependency cjson and update to tag acrn-2022w11.3-180000p

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-hypervisor.bb

update ACRN acrn-2022w12.3-180000p and update license md5sum

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel.bb
recipes-core/acrn/acrn-devicemodel/allow-to-pass-compiler-and-linker-flags.patch
recipes-guests/yocto/core-image-base-package/launch-base.sh

acrn: update to acrn-2022w14.5-180000p
Fix acrn-devicemodel failure. Refreshed patch.
Added new library dependencies.
###################################################
launch-base.sh: update launch script
This sample launch script is generated by config-tool, based
on nuc11tnbi5.xml BOARD and shared SCENARIO

Master next update

---

recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb

b3a5af5 linux-intel-rt-acrn-uos : update to 5.10.109-rt65
b625a45 linux-intel-acrn/5.10: update to v5.10.109

Master kernel updates to v5.10.109

---

conf/layer.conf

layer.conf: drop old releases layer compatibility

---

recipes-core/acrn/acrn-common.inc

Update ACRN release_3.0 RC2

---

conf/distro/include/acrn-demo.inc
docs/dm-verity.md
docs/getting-started.md
docs/qa.md
docs/references.md
docs/slimbootloader.md

acrn-demo.inc: Bump distro version for 4.0 kirkstone release

docs: update document for kirkstone release

---

docs/dm-verity.md
docs/getting-started.md
docs/qa.md
docs/references.md
docs/slimbootloader.md

docs: update document

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Version bump to 4.0

---

recipes-core/acrn/acrn-common.inc
recipes-kernel/linux/acrn-kernel_5.10.inc

ACRN:update release_3.0 RC4

---

recipes-kernel/linux/files/0001-regulator-consumer-Add-missing-stubs-to-regulator-co.patch
recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

e7ba7bb linux-intel-rt-acrn-uos/5.4 : update to 5.4.193-rt74
292669b linux-intel-rt-acrn-uos : update to 5.10.115-rt67
b096c44 linux-intel-acrn/5.10: update to v5.10.115

Kirkstone update

---

recipes-kernel/linux/files/0001-regulator-consumer-Add-missing-stubs-to-regulator-co.patch
recipes-kernel/linux/linux-intel-acrn_5.10.inc
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.10.bb
recipes-kernel/linux/linux-intel-rt-acrn-uos_5.4.bb

83fd547  linux-intel-rt-acrn-uos/5.4 : update to 5.4.193-rt74
7ba532d linux-intel-rt-acrn-uos : update to 5.10.115-rt67
30ce3a0 linux-intel-acrn/5.10: update to v5.10.115

master-next: kernel updates

---

recipes-core/acrn/acrn-common.inc

acrn: update to tag acrn-2022w25.5-180000p

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel.bb
recipes-core/acrn/acrn-devicemodel/dont-build-tools.patch

Refreshed patch. Removed the code, which is not required anymore.

acrn: switch to master branch

---

recipes-kernel/linux/acrn-kernel-rtvm_5.15.bb
recipes-kernel/linux/acrn-kernel-service-vm_5.15.bb
recipes-kernel/linux/acrn-kernel-user-vm_5.15.bb
recipes-kernel/linux/acrn-kernel_5.15.inc
recipes-kernel/linux/files/service-vm_5.15.cfg
recipes-kernel/linux/files/service-vm_5.15.scc
recipes-kernel/linux/files/user-rtvm_5.15.scc
recipes-kernel/linux/files/user-vm_5.15.cfg
recipes-kernel/linux/files/user-vm_5.15.scc

def2c16  acrn-kernel-rtvm/5.15: add recipe
96c00c1 acrn-kernel/5.15: add recipes for service VM & User VM

acrn-kernel/5.15: add recipes for service VM & User VM

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel/allow-to-pass-compiler-and-linker-flags.patch
recipes-core/acrn/acrn-devicemodel/dont-build-tools.patch
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch

acrn: update to tag acrn-2022w29.3-180000p

---

docs/dm-verity.md
docs/getting-started.md
docs/logical-partition.md
docs/slimbootloader.md

https://github.com/intel/meta-acrn/commit/da6bf562f04c95b4b497b75b4a4e71c4b3fc553b

docs: update document for Service and User VM renaming

---

recipes-core/acrn/acrn-common.inc

It includes:
version:v3.0.1
doc: update release_3.0 with changes on master
hv: shell: add cmd to sample vmexit data per-vCPU
hv: cve hotfix: Disable RRSBA on platform using retpoline
modify elementpath version =2.5.0 Modify elementpatch version and update doc part
update debian control file typo issue is a missing ,

acrn: upgrade to v3.0.1

---

conf/layer.conf

layer: drop layer compatibility with old releases

---

recipes-core/acrn/acrn-common.inc

acrn: update to ACRN 3.1 RC2

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.10.bb
recipes-kernel/linux/linux-intel-acrn_5.10.inc

3a51179 linux-intel-acrn-rtvm/5.10: update to v5.10.140
af9054d linux-intel-acrn/5.10: update to v5.10.140

linux-intel-acrn/5.10: update to v5.10.140

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.10.bb
recipes-kernel/linux/linux-intel-acrn_5.10.inc

14ec4d4 linux-intel-acrn-rtvm/5.10: update to v5.10.140
0cab08e linux-intel-acrn/5.10: update to v5.10.140

Master next kernel update

---

recipes-core/acrn/acrn-common.inc

It includes:
doc: update draft 3.1 published docs to include changes on master dm: virtio-blk: fix parameter err
misc: add assertion to check the BDF value
dm: vga: remove all the assertion.
misc: refine upgrade script

acrn: update to tag acrn-2022w39.1-180000p

---

conf/layer.conf

layer.conf: add langdale to LAYERSERIES_COMPAT

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel.bb
recipes-core/acrn/acrn-devicemodel/allow-to-pass-compiler-and-linker-flags.patch
recipes-core/acrn/acrn-devicemodel/dont-build-tools.patch
recipes-core/acrn/acrn-hypervisor/hypervisor-dont-build-pre_build.patch

Release note:
https://projectacrn.github.io/latest/release_notes/release_notes_3.1.html
Fixed Issues:
https://projectacrn.github.io/latest/release_notes/release_notes_3.1.html#fixed-issues-details

acrn: upgrade to v3.1

---

recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

e0b5056 linux-intel-acrn-rtvm/5.15: update to v5.15.71
8813a44 linux-intel-acrn/5.15: update to v5.15.71

 linux-intel-acrn/5.15: update to v5.15.71

---

recipes-guests/yocto/core-image-sato-package/launch-sato.sh
recipes-guests/yocto/core-image-weston-package/launch-weston.sh

9830392 core-image-weston-package: update launch script
f2ed76f core-image-sato-package: update launch script

Update launch scripts

---

conf/distro/acrn-demo-service-vm.conf
conf/distro/acrn-demo-user-vm.conf

Set for both service and user VMs.

distro: set PREFERRED_VERSION to 5.15 kernel

---

recipes-core/acrn/acrn-common.inc

acrn: update to tag acrn-2022w48.3-180000p

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: bump to 4.1

---

conf/distro/include/acrn-demo.inc

acrn-demo.inc: Update to 4.1 version

---

recipes-kernel/linux/files/0001-menuconfig-mconf-cfg-Allow-specification-of-ncurses-.patch
recipes-kernel/linux/linux-intel-acrn-rtvm_5.15.bb
recipes-kernel/linux/linux-intel-acrn_5.15.inc

linux-intel-acrn/5.15: update to 5.15.113
Updated kernel config too.
#########################################
linux-intel-acrn-rtvm/5.15: update to v5.15.113
Updated to latest kernel config too.
Refreshed patch.

linux-intel-acrn/5.15: update to 5.15.113

---

conf/distro/include/acrn-demo.inc

4921a7a acrn-demo.inc: Update to 4.2 version
4d7cba6 acrn-demo.inc: enable usrmerge DISTRO_FEATURE

acrn-demo.inc: enable usrmerge DISTRO_FEATURE

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/acrn-libvirt_6.1.0.bb

set SRCREV_FORMAT for all git repos.

acrn-libvirt: use SRCREV_FORMAT

---

conf/layer.conf

layer.conf: update LAYERSERIES_COMPAT to use nanbield

---

docs/getting-started.md

Added Alder Lake and Raptor Lake to supported platforms. Updated kernel support. Updated ACRN reference links to v3.2.

docs: update documentation

---

classes/acrn-sblimage.bbclass
classes/container-package.bbclass

Update in acrn-sblimage.bbclass too.

container-package.bbclass: Update multiconfig syntax

---

conf/layer.conf

Drop compatibility to nanbield.

layer.conf: update LAYERSERIES_COMPAT to use scarthgap

---

conf/distro/include/acrn-demo.inc
recipes-devtools/python/python3-xmlschema_3.0.1.bb

b5ceafe acrn-demo.inc: fix warning
6937a59 python3-xmlschema: Fix warning

acrn-demo.inc: fix warnings

---

recipes-core/acrn/acrn-common.inc
recipes-core/acrn/acrn-devicemodel.bb
recipes-core/acrn/acrn-devicemodel/0001-No-need-to-build-install-the-tools.patch
recipes-core/acrn/acrn-devicemodel/0002-Makefile-allow-to-pass-compiler-and-linker-flags.patch
recipes-core/acrn/acrn-devicemodel/0003-devicemodel-Makefile-skip-Werror-address-error-check.patch
recipes-core/acrn/files/0001-acrn-Use-std-gnu11-to-fix-build-with-GCC-15.patch
recipes-kernel/linux/files/0001-efi-libstub-Use-std-gnu11-to-fix-build-with-GCC-15.patch
recipes-kernel/linux/files/0002-x86-boot-Use-std-gnu11-to-fix-build-with-GCC-15.patch
recipes-kernel/linux/files/0003-x86-boot-Compile-boot-code-with-std-gnu11-too.patch
recipes-kernel/linux/linux-intel-acrn-rtvm_6.1.bb
recipes-kernel/linux/linux-intel-acrn_6.1.inc

9a176e1 linux: fix gcc-15 build failures
a1a11c2 acrn: fix gcc-15 failures

Fix gcc-15 failures
